project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: 
    site: "@chrphb"  
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
    tools:
      - icon: twitter
        href: https://twitter.com/chrphb
        
metadata-files: [nbdev.yml, sidebar.yml]
