# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorial_ubuntu_nbdev',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/tutorial_ubuntu_nbdev',
                'lib_path': 'tutorial_ubuntu_nbdev'},
  'syms': {'tutorial_ubuntu_nbdev.core': {'tutorial_ubuntu_nbdev.core.foo': ('core.html#foo', 'tutorial_ubuntu_nbdev/core.py')}}}
